server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Handle client-side routing - serve index.html for all routes
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    location /analytics/api/events {
      set $analytics_upstream http://fint-analytics-frontend.fintlabs-no.svc.cluster.local:3000;

      proxy_pass $analytics_upstream/api/events;
      proxy_set_header Host $host;
      proxy_set_header Content-Type application/json;
      proxy_set_header x-analytics-token "change-me";

    }
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
}

