server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Handle client-side routing - serve index.html for all routes
    location = /analytics/api/events {
      proxy_pass http://fint-analytics-frontend.fintlabs-no.svc.cluster.local:3000/api/events;

      proxy_http_version 1.1;
      proxy_set_header Host fint-analytics-frontend.fintlabs-no.svc.cluster.local;
      proxy_set_header Content-Type application/json;
      proxy_set_header x-analytics-token "change-me";
    }
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
}

