apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-test-client
  namespace: fint-core
spec:
  port: 80
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-test-client-v2:latest
  imagePullPolicy: Always
  ingress:
    routes:
      - host: api.felleskomponent.no
        path: /
  imagePullSecrets:
    - ghcr
