apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-test-client
  namespace: fint-core
spec:
  port: 80
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-test-client-v2:latest
  imagePullPolicy: Always
  onePassword:
    itemPath: "vaults/aks-alpha-vault/items/fint-test-client"
  ingress:
    routes:
      - host: alpha.felleskomponent.no
        path: /
        middlewares:
          - name: auth-exclude-assets
  imagePullSecrets:
    - ghcr
